#!/usr/bin/env bash
# =============================================================================
# M0ST container entrypoint
#
# Generates /app/config.yml from environment variables when the file has not
# been mounted by the user.  Passes control to CMD afterwards.
# =============================================================================
set -euo pipefail

CONFIG=/app/config.yml

# ── Only auto-generate when the file is truly absent ─────────────────────────
if [[ ! -f "${CONFIG}" ]]; then
    echo "[entrypoint] config.yml not found — generating from environment variables"

    # Resolve defaults
    LLM_PROVIDER="${LLM_PROVIDER:-none}"
    LLM_MODEL="${LLM_MODEL:-gpt-4o-mini}"
    LLM_API_KEY="${OPENAI_API_KEY:-${ANTHROPIC_API_KEY:-${MISTRAL_API_KEY:-}}}"
    LLM_BASE_URL="${LLM_BASE_URL:-}"
    SQLITE_DB="${SQLITE_DB:-storage/metadata.db}"
    PIPELINE_EVENT_TIMEOUT="${PIPELINE_EVENT_TIMEOUT:-10.0}"
    DYNAMIC_STRATEGY="${DYNAMIC_STRATEGY:-auto}"
    GNN_ARCH="${GNN_ARCH:-gat}"

    cat > "${CONFIG}" <<YAML
# Auto-generated by docker/entrypoint.sh — edit or mount your own config.yml
# to override.

sqlite:
  db_path: ${SQLITE_DB}

tools:
  r2_path: "/opt/radare2/bin"
  gdb_path: ""
  ghidra_path: ""
  windbg_path: ""
  x64dbg_path: ""

dynamic:
  strategy: "${DYNAMIC_STRATEGY}"
  docker_image: "m0st/gdb-trace:latest"

pipeline:
  event_timeout_seconds: ${PIPELINE_EVENT_TIMEOUT}

llm:
  provider: "${LLM_PROVIDER}"
  model: "${LLM_MODEL}"
  api_key: "${LLM_API_KEY}"
  base_url: "${LLM_BASE_URL}"
  temperature: 0.2
  max_tokens: 4096

gnn:
  model_path: ""
  architecture: "${GNN_ARCH}"
  hidden_dim: 128
  out_dim: 64
YAML
    echo "[entrypoint] config.yml written"
else
    echo "[entrypoint] Using existing config.yml"
fi

exec "$@"
